project:
  type: website
  output-dir: docs
  
website:
  title: "Lucia Herrero"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV 

   
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Lucia Herrero"

format:
  html:
    theme: cosmo
    toc: false 

editor: visual 

freeze: auto
