project:
  type: website
  output-dir: docs
  
website:
  title: "Lucia Herrero"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research


  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Lucia Herrero"

format:
  html:
    theme: yeti
    toc: true 

editor: visual 

