### Interests

Neurodevelopment of emotion regulation; intergenerational psychopathology risk; sociocultural resilience; Latine mental health; developmental social, cognitive, and affective neuroscience \(DSCAN) 


### Publications

**Psychology** 

McCrea, C. E. & **Herrero, L.** Social exclusion fails to induce distress-related depletion during food choice. [Manuscript in Review]. Department of Psychological Sciences, Boise State University.         

**Herrero, L.**, & McCrea, C. E. (2023). [Hunger modulates perceptions of food health but not taste in restricted eaters.](https://doi.org/10.3389/fpsyg.2023.1212778) Frontiers in psychology, 14, 1212778. 


**Other**

Farke, A. A., & **Herrero, L.** (2014). Variation in the skull roof of the hadrosaur Gryposaurus illustrated by a new specimen from the Kaiparowits Formation (late Campanian) of southern Utah. In Hadrosaurs (pp. 191–199). Indiana University Press. 

**Herrero, L.**, & Farke, A. A. (2010). [Hadrosaurid dinosaur skin impressions from the Upper Cretaceous Kaiparowits Formation of southern Utah, USA.](https://archives.palarch.nl/index.php/jvp/article/view/451) PalArch’s Journal of Vertebrate Palaeontology, 7(2), 1–7.] 
